### ISSUE TITLE
Create more packages to allow users to depend only on what they need

### ISSUE THREAD

**Issue by juliendelplanque** [juliendelplanque/JRPC#18]
I think packages are missing for the server:
- `JRPC-Server-TCP`
- `JRPC-Server-HTTP`
- `JRPC-Server-Core` This package could be used if users only use the message-processor.

I would like to add support for web socket as transport layer in the future.

For the clients we will have similar packages:
- `JRPC-Client-TCP`
- `JRPC-Client-HTTP`

What do you think @gcotelli ?

**Comment by gcotelli** [comment]
I think it's a good idea. I will do it and also add some groups to the baseline. Can  you add me as an external collaborator to the project so I can assign me the issues I will be working on?

**Comment by juliendelplanque** [comment]
Invitation sent.
