### ISSUE TITLE
Dedicated error handler

### ISSUE THREAD

**Issue by aranega** [juliendelplanque/JRPC#4]
Is there a simple way of being able to add a specific handler for internal JRPC errors? Currently, the only solution I see is to create a kind of error handler registry/chain that could be register in the JRPC server in order to deal with the exception in a specific way (in my case, I want to be able to return a specific object when an exception is caught in the JRPC side).

**Comment by juliendelplanque** [comment]
Is this issue still valid?
I remember we talked together and I think the conclusion was that it needs to be fixed on client side, am I wrong?

**Comment by aranega** [comment]
No, that's it, I close the issue ;)
