### ISSUE TITLE
Server using HTTP transport is not working on Pharo 6.1

### ISSUE THREAD

**Issue by gcotelli** [juliendelplanque/JRPC#8]
I've made some improvements and added a test case doing real network usage (See #7 ) , but now this test is failing on Pharo 6.1 because `ZnEntity` does not understand `json: `. 

I've moved this code to another method, but left it unchanged. So I'm suspecting it wasn't already working. Is still Pharo 6.1 a supported version? In that case we need to change the uses of `ZnEntity json:` to something compatible, or load a new version of Zinc for Pharo 6.

**Comment by juliendelplanque** [comment]
Hello,

I'd prefer to keep the project working on Pharo 6.1 if it does not require too much work.

Maybe we can do a compatibility package with a `#json:` extension method for ZnEntity ?

What do you think?

**Comment by gcotelli** [comment]
I will give it a try. It should be a couple of methods AFAIR.

**Comment by juliendelplanque** [comment]
Maybe they can directly be c/c from Zinc version of Pharo 7/8 ?

Thank you!
